  
version: 0.2
phases:
    build:
       commands:
         - |
           if [! git --git-dir="/dir/.git" diff --quiet]; then 
           apt update;
           fi
         
artifacts:
  files:
    - '**/*'
